"""Add archived_at field to projects

Revision ID: 03d37afa12f2
Revises: 58583a82aff1
Create Date: 2026-01-02 09:44:13.339185

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03d37afa12f2"
down_revision: Union[str, Sequence[str], None] = "58583a82aff1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("archived_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "archived_at")
    # ### end Alembic commands ###
