"""create traffic_logs table

Revision ID: 1aef6fceb806
Revises: 64292884d935
Create Date: 2025-12-23 01:05:52.211671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aef6fceb806'
down_revision: Union[str, Sequence[str], None] = '64292884d935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('response_headers', sa.Text(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_logs_host'), 'traffic_logs', ['host'], unique=False)
    op.create_index(op.f('ix_traffic_logs_id'), 'traffic_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_logs_id'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_host'), table_name='traffic_logs')
    op.drop_table('traffic_logs')
    # ### end Alembic commands ###
