"""add_category_to_api_keys

Revision ID: 3c2a129ac928
Revises: 4324fc4c04a6
Create Date: 2025-12-19 23:28:31.087288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2a129ac928'
down_revision: Union[str, Sequence[str], None] = '4324fc4c04a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'category')
    # ### end Alembic commands ###
