"""create_api_keys_and_modify_llm_config

Revision ID: 4324fc4c04a6
Revises: 60060598b451
Create Date: 2025-12-19 23:08:13.141856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4324fc4c04a6'
down_revision: Union[str, Sequence[str], None] = '60060598b451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('api_base', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.add_column('llm_configs', sa.Column('api_key_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'llm_configs', 'api_keys', ['api_key_id'], ['id'], ondelete='SET NULL')
    op.drop_column('llm_configs', 'api_base')
    op.drop_column('llm_configs', 'api_key')
    op.drop_column('llm_configs', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('llm_configs', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('llm_configs', sa.Column('api_base', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'llm_configs', type_='foreignkey')
    op.drop_column('llm_configs', 'api_key_id')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
