"""Add is_archived field to projects

Revision ID: 58583a82aff1
Revises: f0732575d8bc
Create Date: 2026-01-02 09:12:00.774839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58583a82aff1'
down_revision: Union[str, Sequence[str], None] = 'f0732575d8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_projects_is_archived'), 'projects', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_is_archived'), table_name='projects')
    op.drop_column('projects', 'is_archived')
    # ### end Alembic commands ###
