"""create_asset_tables

Revision ID: c20804e39fe7
Revises: b4ffda872654
Create Date: 2025-12-25 02:37:05.489089

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20804e39fe7'
down_revision: Union[str, Sequence[str], None] = 'b4ffda872654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('type', sa.Enum('URL', 'FORM', 'XHR', name='assettype'), nullable=False),
    sa.Column('source', sa.Enum('HTML', 'JS', 'NETWORK', 'DOM', name='assetsource'), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('request_spec', sa.JSON(), nullable=True),
    sa.Column('response_spec', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('last_task_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_content_hash'), 'assets', ['content_hash'], unique=True)
    op.create_table('asset_discoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_discoveries')
    op.drop_index(op.f('ix_assets_content_hash'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
