"""add_scope_to_targets

Revision ID: f0732575d8bc
Revises: c20804e39fe7
Create Date: 2025-12-25 02:40:03.853964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f0732575d8bc'
down_revision: Union[str, Sequence[str], None] = 'c20804e39fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    target_scope = sa.Enum('DOMAIN', 'SUBDOMAIN', 'URL_ONLY', name='targetscope')
    target_scope.create(op.get_bind())
    op.add_column('targets', sa.Column('scope', target_scope, nullable=False, server_default='DOMAIN'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'scope')
    target_scope = sa.Enum('DOMAIN', 'SUBDOMAIN', 'URL_ONLY', name='targetscope')
    target_scope.drop(op.get_bind())
    # ### end Alembic commands ###
